[[benchmarks]]
day = 1
part = 1

[benchmarks.result]
iterations = 33091
peak_memory = 32192

[benchmarks.result.average_duration]
secs = 0
nanos = 42894

[[benchmarks]]
day = 1
part = 2

[benchmarks.result]
iterations = 53135
peak_memory = 34336

[benchmarks.result.average_duration]
secs = 0
nanos = 68707

[[benchmarks]]
day = 2
part = 1

[benchmarks.result]
iterations = 11050
peak_memory = 88632

[benchmarks.result.average_duration]
secs = 0
nanos = 134039

[[benchmarks]]
day = 2
part = 2

[benchmarks.result]
iterations = 16073
peak_memory = 88688

[benchmarks.result.average_duration]
secs = 0
nanos = 302818

[[benchmarks]]
day = 3
part = 1

[benchmarks.result]
iterations = 7564
peak_memory = 96

[benchmarks.result.average_duration]
secs = 0
nanos = 89264

[[benchmarks]]
day = 3
part = 2

[benchmarks.result]
iterations = 12213
peak_memory = 192

[benchmarks.result.average_duration]
secs = 0
nanos = 140135

[[benchmarks]]
day = 4
part = 1

[benchmarks.result]
iterations = 2342
peak_memory = 112380

[benchmarks.result.average_duration]
secs = 0
nanos = 1547826

[[benchmarks]]
day = 4
part = 2

[benchmarks.result]
iterations = 1143
peak_memory = 643104

[benchmarks.result.average_duration]
secs = 0
nanos = 4213388

[[benchmarks]]
day = 5
part = 1

[benchmarks.result]
iterations = 9572
peak_memory = 18272

[benchmarks.result.average_duration]
secs = 0
nanos = 205326

[[benchmarks]]
day = 5
part = 2

[benchmarks.result]
iterations = 24963
peak_memory = 18272

[benchmarks.result.average_duration]
secs = 0
nanos = 203382

[[benchmarks]]
day = 6
part = 1

[benchmarks.result]
iterations = 8858
peak_memory = 1216512

[benchmarks.result.average_duration]
secs = 0
nanos = 317460

[[benchmarks]]
day = 6
part = 2

[benchmarks.result]
iterations = 45
peak_memory = 1413248

[benchmarks.result.average_duration]
secs = 0
nanos = 113300755

[[benchmarks]]
day = 7
part = 1

[benchmarks.result]
iterations = 346
peak_memory = 696

[benchmarks.result.average_duration]
secs = 0
nanos = 13391867

[[benchmarks]]
day = 7
part = 2

[benchmarks.result]
iterations = 8
peak_memory = 696

[benchmarks.result.average_duration]
secs = 0
nanos = 691024425

[[benchmarks]]
day = 8
part = 1

[benchmarks.result]
iterations = 23913
peak_memory = 21296

[benchmarks.result.average_duration]
secs = 0
nanos = 21685

[[benchmarks]]
day = 8
part = 2

[benchmarks.result]
iterations = 26179
peak_memory = 60464

[benchmarks.result.average_duration]
secs = 0
nanos = 164772

[[benchmarks]]
day = 9
part = 1

[benchmarks.result]
iterations = 3199
peak_memory = 3089632

[benchmarks.result.average_duration]
secs = 0
nanos = 928448

[[benchmarks]]
day = 9
part = 2

[benchmarks.result]
iterations = 9
peak_memory = 1518344

[benchmarks.result.average_duration]
secs = 0
nanos = 572295888

[[benchmarks]]
day = 10
part = 1

[benchmarks.result]
iterations = 4958
peak_memory = 33388

[benchmarks.result.average_duration]
secs = 0
nanos = 245118

[[benchmarks]]
day = 10
part = 2

[benchmarks.result]
iterations = 19143
peak_memory = 16532

[benchmarks.result.average_duration]
secs = 0
nanos = 234003

[[benchmarks]]
day = 11
part = 1

[benchmarks.result]
iterations = 17883
peak_memory = 153696

[benchmarks.result.average_duration]
secs = 0
nanos = 159559

[[benchmarks]]
day = 11
part = 2

[benchmarks.result]
iterations = 403
peak_memory = 9830496

[benchmarks.result.average_duration]
secs = 0
nanos = 11407410

[[benchmarks]]
day = 12
part = 1

[benchmarks.result]
iterations = 80
peak_memory = 984176

[benchmarks.result.average_duration]
secs = 0
nanos = 61460937

[[benchmarks]]
day = 12
part = 2

[benchmarks.result]
iterations = 84
peak_memory = 984176

[benchmarks.result.average_duration]
secs = 0
nanos = 62360152

[[benchmarks]]
day = 13
part = 1

[benchmarks.result]
iterations = 6959
peak_memory = 224

[benchmarks.result.average_duration]
secs = 0
nanos = 245743

[[benchmarks]]
day = 13
part = 2

[benchmarks.result]
iterations = 20636
peak_memory = 224

[benchmarks.result.average_duration]
secs = 0
nanos = 244029

[[benchmarks]]
day = 14
part = 1

[benchmarks.result]
iterations = 6235
peak_memory = 316

[benchmarks.result.average_duration]
secs = 0
nanos = 109915

[[benchmarks]]
day = 14
part = 2

[benchmarks.result]
iterations = 37
peak_memory = 42528

[benchmarks.result.average_duration]
secs = 0
nanos = 137524959

[[benchmarks]]
day = 15
part = 1

[benchmarks.result]
iterations = 1549
peak_memory = 790528

[benchmarks.result.average_duration]
secs = 0
nanos = 2754937

[[benchmarks]]
day = 15
part = 2

[benchmarks.result]
iterations = 1717
peak_memory = 794624

[benchmarks.result.average_duration]
secs = 0
nanos = 2952525

[[benchmarks]]
day = 16
part = 1

[benchmarks.result]
iterations = 1093
peak_memory = 2760880

[benchmarks.result.average_duration]
secs = 0
nanos = 3937492

[[benchmarks]]
day = 16
part = 2

[benchmarks.result]
iterations = 703
peak_memory = 5840368

[benchmarks.result.average_duration]
secs = 0
nanos = 6851278

[[benchmarks]]
day = 17
part = 1

[benchmarks.result]
iterations = 6288
peak_memory = 320

[benchmarks.result.average_duration]
secs = 0
nanos = 2253

[[benchmarks]]
day = 18
part = 1

[benchmarks.result]
iterations = 4116
peak_memory = 628864

[benchmarks.result.average_duration]
secs = 0
nanos = 1227707

[[benchmarks]]
day = 18
part = 2

[benchmarks.result]
iterations = 1743
peak_memory = 358528

[benchmarks.result.average_duration]
secs = 0
nanos = 2743999

[[benchmarks]]
day = 19
part = 1

[benchmarks.result]
iterations = 2358
peak_memory = 517087

[benchmarks.result.average_duration]
secs = 0
nanos = 1184613

[[benchmarks]]
day = 19
part = 2

[benchmarks.result]
iterations = 240
peak_memory = 1333596

[benchmarks.result.average_duration]
secs = 0
nanos = 22893136

[[benchmarks]]
day = 20
part = 1

[benchmarks.result]
iterations = 6
peak_memory = 23315440

[benchmarks.result.average_duration]
secs = 0
nanos = 683403033

[[benchmarks]]
day = 22
part = 1

[benchmarks.result]
iterations = 338
peak_memory = 11

[benchmarks.result.average_duration]
secs = 0
nanos = 15275521

[[benchmarks]]
day = 22
part = 2

[benchmarks.result]
iterations = 9
peak_memory = 139461904

[benchmarks.result.average_duration]
secs = 0
nanos = 578473855

[[benchmarks]]
day = 23
part = 1

[benchmarks.result]
iterations = 6
peak_memory = 781888

[benchmarks.result.average_duration]
secs = 0
nanos = 962575783

[[benchmarks]]
day = 23
part = 2

[benchmarks.result]
iterations = 1599
peak_memory = 488004

[benchmarks.result.average_duration]
secs = 0
nanos = 2647276
